services:
  - type: web
    name: minha-api-backend
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm install && npx prisma generate && npx prisma migrate deploy
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        value: file:/app/data/prod.db
    disk:
      name: sqlite-disk
      mountPath: /app/data
      sizeGB: 1
